name: Deploy to Staging Env
on:
    push:
        branches:
            - stg

# Cancel all previous workflow runs for the same branch that have not yet completed.
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    bundle:
        name: Bundle Assets
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
            - name: Install NPM dependencies
              run: npm ci
            - name: Build assets
              run: npm run build
            - name: Upload dist folder
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: wp-content/themes/veterans-archive/dist
    deploy:
        name: Deploy to WP Engine
        runs-on: ubuntu-latest
        needs: [bundle]
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: wp-content/themes/veterans-archive/dist/
            - name: GitHub Action Deploy to WP Engine
              if: success()
              uses: wpengine/github-action-wpe-site-deploy@v3
              with:
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
                  WPE_ENV: choctawvetstg
